### ISSUE TITLE
Fix for: java.lang.NoClassDefFoundError:failed resolution of :Lorg/apache/http/ProtocolVersion

### ISSUE THREAD

**Issue by dlandi** [LRP-sgravel/Xamarin.Forms.SKMaps#3]
Thanks for fixing the nuget issues. I added my own developer key and then encountered this error:

> Java.Lang.NoClassDefFoundError
>   Message=Failed resolution of: Lorg/apache/http/ProtocolVersion;

According to this [link ](https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve), it can be fixed with adding the following line in the android.manifest application tag: 

`<uses-library android:name="org.apache.http.legacy" android:required="false" />`

![image](https://user-images.githubusercontent.com/3196088/73163687-bf0f4880-40f0-11ea-8549-923abc78d809.png)

And that has fixed the issue for me.

**Comment by sgravel-dev** [comment]
I’m not having this issue, this is akward.  According to Google (https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library) this is only required if GooglePlayServices.Maps is version 16.0 and the sample is on version 11.  Did you update it?

**Comment by dlandi** [comment]
Nope. I just downloaded the zip, added my developer key and ran it. On a API 28 emulator, and my Samsung Galaxy Note 9. Both had the same issue. 

(I sent you a note on LinkedIn, btw)

**Comment by sgravel-dev** [comment]
Updated the Nuget to version Maps 16.1 and it works fine now.

Thanks for your time!
